server:
  port: 6969
  context-path: /
spring:
  datasource:
      username: root
      password: 123456jpp.
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://119.23.205.252/bigdata?useUnicode=true&characterEncoding=utf8

  jpa:
    generate-ddl: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql